<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * example site extension layout template
 */

$owApp = OntoWiki::getInstance();

$rdform = $owApp->extensionManager->getComponentHelper('rdform');
$rdform->siteInit();

// this is the standard template data
$templateData   = $this->templateData;
$title = $this->literal(array('uri' => $this->modelUri, 'property' => EF_RDFS_NS . 'label', 'plain' => true));
?><!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xmlns:dc="http://purl.org/dc/terms/" xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <meta charset="UTF-8">
    <title><?= $title . ': ' . $this->title ?></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="generator" content="<?= $this->generator ?>" />

    <link rel="alternate" type="application/rdf+xml" href="<?= $this->resourceUri ?>.rdf" />
    <link rel="pingback" href="<?= $this->pingbackUrl ?>" />

    <link rel="<?= $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>" href="<?= $this->resourceUri?>" />

    <?php
    // includes stylesheets from rdform and inline styles
    echo $rdform->getStyles();
    ?>

</head>

<body<?php
    foreach ($this->namespaces as $prefix => $ns): ?><?= ' xmlns:' . $prefix . '="' . $ns . '"' ?><?php endforeach; ?>>
<div class="container">

    <header class="header">

        <?php
        $navResource = $this->templateOptions()->getValue('http://rdfs.org/ns/void#rootResource');
        $navOptions = array(
            'navResource' => $navResource,
            //'navId' => 'nav-main',
            'activeUrl' => $this->resourceUri,
            'listClass' => 'list-inline',
            //'navClass' => 'navbar'
        );
        ?>

        <h1 class="title"><?= $title ?></h1>

    </header>

    <div class="container content-container">

    <?php if ( ! $owApp->getUser()->isAnonymousUser() ) { ?>

        <div class="menu pull-left">
            Angemeldet als: <?php echo $owApp->getUser()->getUsername(); ?> |
            <a href="<?php echo $this->urlBase ?>application/logout">Abmelden</a>
        </div>

        <div id="menu" class="menu pull-right">
            <a href="<?= $this->Url(array('uri' => $this->resourceUri, 'stayOnSite' => false)) ?>"><?= $this->_('backend') ?></a><!-- should always be displayed -->
            <a class="rdform-edit-btn" href="#"><?= $this->_('edit') ?></a> | 
            <a class="rdform-new-btn" href="#"><?= $this->_('new') ?></a>
        </div>
        <br clear="both" />

    <?php } ?>

    <?= $this->renderx($this->templateData); ?>

    </div>

    <hr>
    <footer>
        <?php
            $copy = $this->literal(array('uri' => $this->modelUri, 'property' => 'http://creativecommons.org/ns#attributionName'));
            if ($copy != null) :
        ?>
        <p>&copy; <?= date('Y') . ' ' . $copy ?></p>
        <?php endif ?>
    </footer>
</div> <!-- /container -->

<!-- jQuery -->
<script type="text/javascript" src="<?= $this->themeUrlBase ?>scripts/libraries/jquery-1.9.1.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/bootstrap.js"></script>
<?php
    // includes rdform scripts, for perfomance resons at the end
    echo $rdform->getScripts();
?>

</body>
</html>
