<?php

$owApp = OntoWiki::getInstance();

if ($this->has('redirectUri')): ?>
	    <input type="hidden" id="redirectUri" value="<?php echo $this->redirectUri ?>"/>
<?php endif; ?>
</script>
<input type="hidden" id="urlBase" value="<?php echo $this->urlBase ?>" />
<input type="hidden" id="modelIri" label="model" value="<?php echo $this->selectedModel ?>" />
<form action="#" class="form-horizontal rdform" role="form"></form>

<script language="JavaScript">
	var modelIri = '<?= $this->selectedModel ?>';
	var resourceIri = '<?= $this->selectedResource ?>';
	var redirectUri = $("#redirectUri").val();
	var template = "form_pfarrerbuch-Person.html";
	
	var owCon = new OntoWikiConnection(urlBase + 'jsonrpc');
	owCon.getResource( modelIri, resourceIri, function( resData ) {
		var hash = resData.dataHash;		
		var owRdform = new OntoWikiRDForm({
			template: template,
			hooks: "hooks_pfarrerbuch.js",
			data: resData.data
		});
		
		owRdform.init( function( result ) {
            
            owCon.updateResource( modelIri, resourceIri, hash, result, function( updateResult ) {
            	window.location.href = decodeURIComponent(redirectUri);
            } );
		});
	});
</script>

<style type="text/css">
.rdform, .rdform-alert {
	max-width: 800px;
}
	
@font-face{
font-family:'Glyphicons Halflings';
src:url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.eot);
src:url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.eot?#iefix) format('embedded-opentype'),url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.woff) format('woff'),url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.ttf) format('truetype'),url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular) format('svg')
}		
</style>
