<?php if ($this->has('redirectUri')): ?>
    <input type="hidden" id="redirectUri" value="<?php echo $this->redirectUri ?>"/>
<?php endif; ?>
<input type="hidden" id="modelIri" label="model" value="<?php echo $this->selectedModel ?>" />
<input type="hidden" id="resourceIri" label="resource" value="<?php echo $this->selectedResource ?>" />
DataHash: <input type="text" id="dataHash" label="dataHash" />
<input type="checkbox" id="editable" disabled="true" /> editable<br />

<!--<textarea id="jsonResult"></textarea>-->

<p><hr /></p>

<form action="#" class="form-horizontal rdform" role="form"></form>

<script language="JavaScript">
	var modelIri = '<?= $this->selectedModel ?>';
	var resourceIri = '<?= $this->selectedResource ?>';

	var con = new OntoWikiConnection(urlBase + 'jsonrpc');
	con.getResource( modelIri, resourceIri );
</script>

