<?php if ($this->has('redirectUri')): ?>
    <input type="hidden" id="redirectUri" value="<?php echo $this->redirectUri ?>"/>
<?php endif; ?>
<input type="hidden" id="modelIri" label="model" value="<?php echo $this->selectedModel ?>" />
<input type="hidden" id="resourceIri" label="resource" value="<?php echo $this->selectedResource ?>" />
DataHash: <input type="text" id="dataHash" label="dataHash" />
<input type="checkbox" id="editable" disabled="true" /> editable<br />

<!--
<textarea id="jsonResult"></textarea>
-->

<p><hr /></p>

<form action="#" class="form-horizontal rdform" role="form"></form>

<script language="JavaScript">
	var modelIri = '<?= $this->selectedModel ?>';
	var resourceIri = '<?= $this->selectedResource ?>';

	var con = new OntoWikiConnection(urlBase + 'jsonrpc');
	con.getResource( modelIri, resourceIri );
</script>

<style type="text/css">
* {
    box-sizing: border-box;
}
.rdform {
	max-width: 800px;
}

.form-group {
	margin-bottom: 15px;
}
.form-group:after {
	clear: both;
	content: " ";
display: table;
}
.col-xs-3,
.col-xs-9 {
	float: left;
	padding-left: 15px;
	padding-right: 15px;
	position: relative;
}
.col-xs-3 {
	width: 25%;
	
}
.col-xs-9 {
	width: 75%;
}
.form-horizontal .control-label {
	text-align: right;
}

</style>
